apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

secretGenerator:
  - name: riditools
    type: Opaque
    files:
      - ormconfig.json

resources:
  - cronjob.yaml

# namespace to deploy all Resources to
namespace: default
