# Default values for bluesky-pds.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/bluesky-social/pds
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "0.4.59"

pds:
  config:
    hostname: "pds.example.com"
    secrets:
      # openssl rand --hex 16
      jwtSecret: ""
      # openssl ecparam --name secp256k1 --genkey --noout --outform DER | tail --bytes=+8 | head --bytes=32 | xxd --plain --cols 32
      adminPassword: ""
      # openssl rand --hex 16
      plcRotationKey: ""
      ## Set the value for existingSecret to use a pre-created secret for jwtSecret, adminPassword and plcRotationKey
      #existingSecret : ""
    dataDir: "/pds"
    blobstoreLocation: "/pds/blocks"
    didPlcUrl: "https://plc.directory"
    bskyAppViewUrl: "https://api.bsky.app"
    bskyAppViewDid: "did:web:api.bsky.app"
    reportSvcUrl: "https://mod.bsky.app"
    reportSvcDid: "did:plc:ar7c4by46qjdydhdevvrndac"
    crawlers: "https://bsky.network"
  dataStorage:
    size: 10Gi
    mountPath: "/pds"
    storageClass: null

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext:
  {}
  # fsGroup: 2000

securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: false
  className: ""
  annotations:
    {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: pds.example.com
      paths:
        - path: /
          pathType: Prefix
  tls: []
  #  - secretName: bluesky-pds-tls
  #    hosts:
  #      - pds.example.com

resources:
  {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
