apiVersion: apps/v1
kind: Deployment
metadata:
  name: animeta-backend-ts
  labels:
    app: animeta-backend-ts
    keel.sh/policy: force
spec:
  replicas: 1
  selector:
    matchLabels:
      app: animeta-backend-ts
  template:
    metadata:
      labels:
        app: animeta-backend-ts
    spec:
      containers:
      - name: backend
        image: gcr.io/ditto-1470749749381/animeta-backend-ts
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
        env:
        - name: NODE_ENV
          value: production
        - name: SENTRY_DSN
          value: "https://deb70af1222e49a98b699584f9819f79@o120476.ingest.sentry.io/6187990"
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /app/secrets/google-credentials.json
        - name: ANIMETA_MEDIA_STORAGE_URL
          value: "gs://animeta-static/media/"
        envFrom:
        - secretRef:
            name: animeta-backend-ts
        resources:
          limits:
            memory: "512Mi"
          requests:
            memory: "256Mi"
        readinessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 10
        volumeMounts:
        - mountPath: /app/backend-ts/ormconfig.json
          name: secret
          subPath: backend-ts-ormconfig.json
        - mountPath: /app/secrets
          name: secret
      volumes:
      - name: secret
        secret:
          secretName: animeta-backend-ts
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: NotIn
                values:
                - "true"
