apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/acme-challenge-type: http01
    cert-manager.io/issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
  name: animeta-api
spec:
  rules:
  - host: api.animeta.net
    http:
      paths:
      - backend:
          serviceName: animeta-backend-ts
          servicePort: 8081
        path: /api/v4
  - host: api.animeta.net
    http:
      paths:
      - backend:
          serviceName: animeta-backend-ts
          servicePort: 8082
        path: /api/v5
  - host: api.animeta.net
    http:
      paths:
      - backend:
          serviceName: animeta-backend-ts
          servicePort: 8082
        path: /api/admin/v1
  - host: api.animeta.net
    http:
      paths:
      - backend:
          serviceName: animeta-backend-ts
          servicePort: 8082
        path: /graphql
  tls:
  - hosts:
    - api.animeta.net
    secretName: animeta-tls
