apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

secretGenerator:
  - name: animeta
    type: Opaque
    env: secrets.env
    files:
      - google-credentials.json
      - backend-config.properties
  - name: animeta-backend-ts
    type: Opaque
    env: backend-ts-secrets.env
    files:
      - backend-ts-ormconfig.json
      - google-credentials.json

configMapGenerator:
  - name: animeta-frontend
    files:
      - frontend-config.json

resources:
  - deployment-backend-ts.yaml
  - service-backend-ts.yaml
  - deployment-frontend.yaml
  - service-frontend.yaml
  - ingress.yaml
  - cronjob.yaml

# namespace to deploy all Resources to
namespace: default
