{{- if not .Values.pds.config.secrets.existingSecret }} 
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "bluesky-pds.fullname" . }}-secret"
  labels: 
    {{- include "bluesky-pds.labels" . | nindent 4 }}
data:
  jwtSecret: {{ .Values.pds.config.secrets.jwtSecret | b64enc | quote }}
  adminPassword: {{ .Values.pds.config.secrets.adminPassword | b64enc | quote }}
  plcRotationKey: {{ .Values.pds.config.secrets.plcRotationKey | b64enc | quote }}
type: Opaque
{{- end }}
