apiVersion: v1
kind: Service
metadata:
  name: {{ include "bluesky-pds.fullname" . }}
  labels:
    {{- include "bluesky-pds.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: pds-port
      protocol: TCP
      name: pds-port
  selector:
    {{- include "bluesky-pds.selectorLabels" . | nindent 4 }}
