environments:
  default:
    values:
      - ../env.yaml

repositories:
- name: ingress-nginx
  url: https://kubernetes.github.io/ingress-nginx
- name: jetstack
  url: https://charts.jetstack.io
- name: keel-charts
  url: https://charts.keel.sh
- name: bitnami
  url: https://charts.bitnami.com/bitnami
- name: bitnami-full-index
  url: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami

releases:
- name: nginx-ingress
  namespace: nginx-ingress
  chart: ingress-nginx/ingress-nginx
  version: 4.4.0
  set:
    - name: controller.ingressClassResource.default
      value: "true"

- name: cert-manager
  namespace: cert-manager
  chart: jetstack/cert-manager
  version: v1.10.0
  set:
    - name: installCRDs
      value: "true"

- name: keel
  namespace: kube-system
  chart: keel-charts/keel
  version: 0.8.22
  values:
  - keel/values.yaml.gotmpl

- name: postgres
  namespace: default
  chart: bitnami/postgresql
  version: 10.16.2
  values:
  - postgres/values.yaml.gotmpl

- name: mastodon
  namespace: default
  chart: ./mastodon
  values:
  - mastodon/values.yaml.gotmpl
