environments:
  default:
    values:
      - ../env.yaml

repositories:
- name: ingress-nginx
  url: https://kubernetes.github.io/ingress-nginx
- name: jetstack
  url: https://charts.jetstack.io
- name: keel-charts
  url: https://charts.keel.sh
- name: bitnami
  url: https://charts.bitnami.com/bitnami

releases:
- name: nginx-ingress
  namespace: nginx-ingress
  chart: ingress-nginx/ingress-nginx
  version: 3.15.2
  values:
  - nginx-ingress/values.yaml

- name: cert-manager
  namespace: cert-manager
  chart: jetstack/cert-manager
  version: v0.15.0

- name: keel
  namespace: kube-system
  chart: keel-charts/keel
  version: 0.8.22
  values:
  - keel/values.yaml.gotmpl

- name: postgres
  namespace: default
  chart: bitnami/postgresql
  version: 8.6.4
  values:
  - postgres/values.yaml.gotmpl
