environments:
  default:
    values:
      - ../env.yaml

repositories:
- name: ingress-nginx
  url: https://kubernetes.github.io/ingress-nginx
- name: jetstack
  url: https://charts.jetstack.io
- name: keel-charts
  url: https://charts.keel.sh
- name: bitnami
  url: https://charts.bitnami.com/bitnami
- name: bitnami-full-index
  url: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
- name: vm
  url: https://victoriametrics.github.io/helm-charts/
- name: grafana
  url: https://grafana.github.io/helm-charts

releases:
- name: vmsingle
  namespace: monitoring
  chart: vm/victoria-metrics-single
  version: 0.8.50
  values:
  - vmsingle/values.yaml

- name: grafana
  namespace: monitoring
  chart: grafana/grafana
  version: 6.50.0
  values:
  - grafana/values.yaml

- name: nginx-ingress
  namespace: nginx-ingress
  chart: ingress-nginx/ingress-nginx
  version: 4.4.0
  set:
    - name: controller.ingressClassResource.default
      value: "true"

- name: cert-manager
  namespace: cert-manager
  chart: jetstack/cert-manager
  version: v1.10.0
  set:
    - name: installCRDs
      value: "true"

- name: postgres
  namespace: default
  chart: bitnami-full-index/postgresql
  version: 10.16.2
  values:
  - postgres/values.yaml.gotmpl

- name: valkey
  namespace: default
  chart: bitnami/valkey
  version: 2.2.3
  values:
  - valkey/values.yaml.gotmpl

- name: mastodon
  namespace: default
  chart: ./mastodon
  values:
  - mastodon/values.yaml.gotmpl

- name: bluesky-pds
  namespace: default
  chart: ./bluesky-pds
  values:
  - bluesky-pds/values.yaml.gotmpl
